use super::collector::MetricsSnapshot;
use serde_json;

pub struct MetricsExporter;

impl MetricsExporter {
    pub fn export_json(snapshot: &MetricsSnapshot) -> String {
        serde_json::to_string_pretty(snapshot).unwrap_or_default()
    }

    pub fn export_prometheus(snapshot: &MetricsSnapshot) -> String {
        let mut output = String::new();

        output.push_str("# UltraBalancer Prometheus Metrics\n");
        output.push_str("# Generated by UltraBalancer v3.0.0\n");
        output.push_str(&format!(
            "# Uptime: {} seconds\n\n",
            snapshot.uptime_seconds
        ));

        output.push_str("## Global Request Metrics\n");
        output.push_str("# HELP ultrabalancer_requests_total Total number of requests received by the load balancer\n");
        output.push_str("# TYPE ultrabalancer_requests_total counter\n");
        output.push_str(&format!(
            "ultrabalancer_requests_total {}\n\n",
            snapshot.total_requests
        ));

        output.push_str("# HELP ultrabalancer_requests_success_total Total number of successfully proxied requests\n");
        output.push_str("# TYPE ultrabalancer_requests_success_total counter\n");
        output.push_str(&format!(
            "ultrabalancer_requests_success_total {}\n\n",
            snapshot.successful_requests
        ));

        output.push_str(
            "# HELP ultrabalancer_requests_failed_total Total number of failed requests\n",
        );
        output.push_str("# TYPE ultrabalancer_requests_failed_total counter\n");
        output.push_str(&format!(
            "ultrabalancer_requests_failed_total {}\n\n",
            snapshot.failed_requests
        ));

        output.push_str("## Response Time Metrics\n");
        output.push_str(
            "# HELP ultrabalancer_response_time_ms Response time in milliseconds (histogram)\n",
        );
        output.push_str("# TYPE ultrabalancer_response_time_ms histogram\n");
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"1\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"5\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"10\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"25\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"50\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"100\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"250\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"500\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"1000\"}} 0\n"
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_bucket{{le=\"+Inf\"}} {}\n",
            snapshot.total_requests
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_sum {}\n",
            snapshot.avg_response_time_ms * snapshot.total_requests as f64
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_count {}\n\n",
            snapshot.total_requests
        ));

        output.push_str(
            "# HELP ultrabalancer_response_time_ms_seconds Response time in seconds (summary)\n",
        );
        output.push_str("# TYPE ultrabalancer_response_time_ms_seconds summary\n");
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds{{quantile=\"0.5\"}} {}\n",
            snapshot.p50_response_time_ms / 1000.0
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds{{quantile=\"0.9\"}} {}\n",
            snapshot.p95_response_time_ms / 1000.0
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds{{quantile=\"0.95\"}} {}\n",
            snapshot.p95_response_time_ms / 1000.0
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds{{quantile=\"0.99\"}} {}\n",
            snapshot.p99_response_time_ms / 1000.0
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds_sum {}\n",
            snapshot.avg_response_time_ms * snapshot.total_requests as f64 / 1000.0
        ));
        output.push_str(&format!(
            "ultrabalancer_response_time_ms_seconds_count {}\n\n",
            snapshot.total_requests
        ));

        output.push_str("## Uptime and Throughput\n");
        output.push_str("# HELP ultrabalancer_uptime_seconds_total Total uptime in seconds\n");
        output.push_str("# TYPE ultrabalancer_uptime_seconds_total counter\n");
        output.push_str(&format!(
            "ultrabalancer_uptime_seconds_total {}\n\n",
            snapshot.uptime_seconds
        ));

        output.push_str("# HELP ultrabalancer_requests_per_second Current requests per second\n");
        output.push_str("# TYPE ultrabalancer_requests_per_second gauge\n");
        output.push_str(&format!(
            "ultrabalancer_requests_per_second {}\n\n",
            snapshot.requests_per_second
        ));

        output.push_str("## Error Rate\n");
        output.push_str(
            "# HELP ultrabalancer_error_ratio Current error ratio (errors / total requests)\n",
        );
        output.push_str("# TYPE ultrabalancer_error_ratio gauge\n");
        let error_ratio = if snapshot.total_requests > 0 {
            snapshot.failed_requests as f64 / snapshot.total_requests as f64
        } else {
            0.0
        };
        output.push_str(&format!("ultrabalancer_error_ratio {}\n\n", error_ratio));

        output.push_str("## Backend Metrics\n");
        output.push_str(
            "# HELP ultrabalancer_backend_requests_total Total requests handled by each backend\n",
        );
        output.push_str("# TYPE ultrabalancer_backend_requests_total counter\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_requests_total{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.total_requests
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_requests_success_total Total successful requests per backend\n");
        output.push_str("# TYPE ultrabalancer_backend_requests_success_total counter\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_requests_success_total{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.successful_requests
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_requests_failed_total Total failed requests per backend\n");
        output.push_str("# TYPE ultrabalancer_backend_requests_failed_total counter\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_requests_failed_total{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.failed_requests
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_response_time_seconds Average response time per backend in seconds\n");
        output.push_str("# TYPE ultrabalancer_backend_response_time_seconds gauge\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_response_time_seconds{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label,
                backend_label,
                metrics.avg_response_time_ms / 1000.0
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_response_time_last_seconds Last response time per backend in seconds\n");
        output.push_str("# TYPE ultrabalancer_backend_response_time_last_seconds gauge\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_response_time_last_seconds{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.last_response_time_ms / 1000.0
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_active_connections Current active connections to each backend\n");
        output.push_str("# TYPE ultrabalancer_backend_active_connections gauge\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_active_connections{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.active_connections
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_status Health status of each backend (1 = healthy, 0 = unhealthy)\n");
        output.push_str("# TYPE ultrabalancer_backend_status gauge\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            let status = if metrics.status == "up" { 1 } else { 0 };
            output.push_str(&format!(
                "ultrabalancer_backend_status{{backend=\"{}\",host=\"{}\",status=\"{}\"}} {}\n",
                backend_label, backend_label, metrics.status, status
            ));
        }
        output.push_str("\n");

        output.push_str("# HELP ultrabalancer_backend_weight Configured weight for each backend\n");
        output.push_str("# TYPE ultrabalancer_backend_weight gauge\n");
        for (backend, _) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            output.push_str(&format!(
                "ultrabalancer_backend_weight{{backend=\"{}\",host=\"{}\"}} 100\n",
                backend_label, backend_label
            ));
        }
        output.push_str("\n");

        output.push_str("## Health Check Metrics\n");
        output.push_str("# HELP ultrabalancer_healthy_backends Total number of healthy backends\n");
        output.push_str("# TYPE ultrabalancer_healthy_backends gauge\n");
        let healthy_count = snapshot
            .backend_metrics
            .iter()
            .filter(|(_, m)| m.status == "up")
            .count();
        output.push_str(&format!(
            "ultrabalancer_healthy_backends {}\n",
            healthy_count
        ));
        output.push_str("\n");

        output
            .push_str("# HELP ultrabalancer_total_backends Total number of configured backends\n");
        output.push_str("# TYPE ultrabalancer_total_backends gauge\n");
        output.push_str(&format!(
            "ultrabalancer_total_backends {}\n\n",
            snapshot.backend_metrics.len()
        ));

        output.push_str("## Backend Error Rate\n");
        output.push_str("# HELP ultrabalancer_backend_error_ratio Error ratio per backend\n");
        output.push_str("# TYPE ultrabalancer_backend_error_ratio gauge\n");
        for (backend, metrics) in &snapshot.backend_metrics {
            let backend_label = Self::sanitize_label(backend);
            let backend_error_ratio = if metrics.total_requests > 0 {
                metrics.failed_requests as f64 / metrics.total_requests as f64
            } else {
                0.0
            };
            output.push_str(&format!(
                "ultrabalancer_backend_error_ratio{{backend=\"{}\",host=\"{}\"}} {}\n",
                backend_label, backend_label, backend_error_ratio
            ));
        }

        output
    }

    fn sanitize_label(label: &str) -> String {
        label.replace(['"', ' ', ':'], "_")
    }
}
